### ISSUE TITLE
Invalid Request Error 

### ISSUE THREAD

**Issue by jaredforth** [NopeCHALLC/nopecha-extension#109]
I have purchased a subscription and am following the docs:

```ts
const { Configuration, NopeCHAApi } = require("nopecha");

export const solveHCaptcha = async () => {
  const configuration = new Configuration({
    apiKey: process.env.NOPECHA_API_KEY,
  });
  const nopecha = new NopeCHAApi(configuration);

  const token = await nopecha.solveToken({
    type: "hcaptcha",
    sitekey: "58366d97-3e8c-4b57-a679-4a41c8423be3",
    url: "https://nopecha.com/demo/hcaptcha#easy",
  });

  console.log(token);

  const balance = await nopecha.getBalance();

  console.log(balance);
};
```

When I run this, the following response is returned:

```
InvalidRequestError: Invalid request
    at NopeCHAApi.handle_error_response (.../node_modules/nopecha/nopecha.js:143:20)
    at NopeCHAApi.post (.../node_modules/nopecha/nopecha.js:197:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NopeCHAApi.solve (.../node_modules/nopecha/nopecha.js:204:17)
    at async NopeCHAApi.solveToken (.../node_modules/nopecha/nopecha.js:222:16)

Node.js v20.11.1
```

Hitting the API directly returns:

```
{
    "error": 10,
    "message": "Invalid request",
    "type": "Invalid type"
}
```

**Comment by kacperslenzak** [comment]
getting the same error in python using code provided in docs

```
job_id = requests.post(API, json={
                'type': 'hcaptcha',
                'sitekey': captcha_data['captcha_sitekey'],
                'url': URL,
                'key': KEY,
            })
```

returning:
`{'error': 10, 'message': 'Invalid request', 'type': 'Invalid type'}`

**Comment by shoval6** [comment]
Are you sure the URL supposed to be : "https://nopecha.com/demo/hcaptcha#easy" ?
according docs : URL where the hCaptcha is found.
